name: Refactor Code and Push to Master

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  refactor-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master  # Ensure we are on the master branch

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Run the refactoring script
    - name: Refactor code
      run: |
        python refactor.py  # Executes the refactoring script

    # Step 5: Commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.name "praveenkumar911"
        git config --global user.email "praveenkumarpalaboyina@gmail.com"
        git add .
        git commit -m "Refactored code using LLM" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.CLASS_TOKEN }}
